apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end

spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front-enf
     spec:
       containers:
         - name: bginx-container
           image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end
